@url =http://localhost:5458/tournament

POST {{url}}
Content-Type: application/json
     

{
  "EventName": "Turkey Time",
  "StartDate": "2024-11-23",
  "EndDate": "2024-11-23",
  "NumberOfRings" : 2
}
###
 GET {{url}}

###
 DELETE {{url}}/1

###
GET {{url}}/150b4748-bb8d-4851-b48c-436154ce8eb7