POST http://localhost:5458/tournament
Content-Type: application/json

{
  "EventName": "Turkey Time",
  "StartDate": "2023-11-23T00:00:00Z",
  "EndDate": "2023-11-23T00:00:00Z",
  "NumberOfLanes" : 2
}
