name: $(Date:yyyy).$(Date:MMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - main    

pool:
  vmimage: "ubuntu-latest"



variables: 
  # url: https://tfs.saif.com/SAIFCodeCollection/Framework%20Product/_git/Framework.CoreServices.LoggingApi?path=%2FPipelines%2Fbuild-vars.yml
  - template: vars.yml

stages:  
- stage: infrastructure
  jobs:
  - template: templates/terraform-cloud-cli.yml
    parameters:
      TerraformDirectory: $(TerraformDirectory)
      ApplicationName: $(AppName)
      TerraformCommandOptions: $(TerraformCommandOptions)
      environment: $(environment)
- template: templates/staticwebapp.yml
  parameters:
    AppLocation: $(AppLocation)
    ApiLocation: $(ApiLocation)  
    ConfigFileLocation: $(ConfigFileLocation)
    outputlocation: $(OutputLocation)
