name: $(Date:yyyy).$(Date:MMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - main    
  paths:
    include:
    - src/Functions/RingApi*
    - src/Functions/FunctionHelper*    

pool:
  vmimage: "ubuntu-latest"

variables: 
  - template: vars.yml

stages:  
- template: templates/azurefunction-builddeploy.yml
  parameters:
    AppName: $(AppName)
    ApiName: RingApi  
    SourceDirectory: $(FunctionSourceDirectory)
