parameters:
- name: AppLocation
  type: string
- name: ApiLocation
  type: string
- name: ConfigFileLocation
  type: string
- name: OutputLocation
  type: string

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    steps:
    - task: AzureStaticWebApp@0
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)' 
        app_location: ${{parameters.AppLocation}}
        #app_build_command: # string. App build command. 
        output_location: ${{parameters.OutputLocation}} 
        api_location: ${{parameters.ApiLocation}}
        #api_build_command: # string. Api build command. 
        #routes_location: # string. Routes location. 
        config_file_location: ${{parameters.ConfigFileLocation}}
        #skip_app_build: # boolean. Skip app build. 
        #skip_api_build: # boolean. Skip api build. 
        #is_static_export: # boolean. Set static export. 
        #verbose: # boolean. Verbose. 
        #build_timeout_in_minutes: # string. Build timeout in minutes. 
        azure_static_web_apps_api_token: $(swa-token)
        #deployment_environment: # string. Deployment Environment. 
        #production_branch: # string. Production Branch. 
        #data_api_location: # string. Data api location.