POST http://localhost:7071/api/Create

{
  "EventName": "Christmas Time",
  "StartDate": "2023-12-23T00:00:00Z",
  "EndDate": "2023-12-23T00:00:00Z",
  "NumberOfLanes" : 2
}

### Get ALl 
GET http://localhost:7071/api/GetAll

### Put
PUT http://localhost:7071/api/5181d301-eab7-4c3a-a99c-398e3b2c1447

{
  "EventName": "Christmas Time Tournament",
  "StartDate": "2023-12-23T00:00:00Z",
  "EndDate": "2023-12-23T00:00:00Z",
  "NumberOfLanes" : 4
}

### Delete 
DELETE http://localhost:7071/api/5181d301-eab7-4c3a-a99c-398e3b2c1447


