name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'  # Replace with your .NET Core version

    - name: Restore dependencies
      run: dotnet restore tests/Functions.Tests.Integration/Functions.Tests.Integration.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test tests/Functions.Tests.Integration/Functions.Tests.Integration.csproj --no-restore --verbosity normal
